"""The migration chain must stay in step with the models.

Autogenerate is not a safety net — it only reflects what someone remembered to
generate. These tests fail the moment a model changes without a migration (DR1).
"""
from __future__ import annotations

import asyncio
import os
from pathlib import Path

import pytest
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import Enum as SAEnum
from sqlalchemy import text
from sqlalchemy.ext.asyncio import create_async_engine

import app.models  # noqa: F401 — registers metadata
from alembic import command
from app.config import get_settings
from app.db import Base


def _cfg(url: str) -> Config:
    root = Path(__file__).parents[1]
    cfg = Config(str(root / "alembic.ini"))
    cfg.set_main_option("script_location", str(root / "alembic"))
    os.environ["ALEMBIC_DATABASE_URL"] = url
    return cfg


async def test_models_match_the_migration_chain(engine):
    """`alembic check` — there must be no pending autogenerate diff."""
    try:
        await asyncio.to_thread(command.check, _cfg(get_settings().test_database_url))
    except AutogenerateDiffsDetected as e:
        pytest.fail(
            "The models have drifted from the migrations. Generate one:\n"
            "  cd services/api && uv run alembic revision --autogenerate -m '<what changed>'\n\n"
            f"{e}"
        )


async def test_downgrade_then_upgrade_round_trips():
    """Postgres ENUM types outlive DROP TABLE, so a naive downgrade leaves them
    behind and the next upgrade fails with "type already exists".

    Runs against its own throwaway database — the round trip destroys the schema,
    which would wipe data other tests are relying on.
    """
    base = get_settings().test_database_url
    admin_url = base.rsplit("/", 1)[0] + "/postgres"
    scratch_name = "volt_test_migrations"
    scratch_url = base.rsplit("/", 1)[0] + f"/{scratch_name}"

    admin = create_async_engine(admin_url, isolation_level="AUTOCOMMIT")
    async with admin.connect() as conn:
        await conn.execute(text(f"DROP DATABASE IF EXISTS {scratch_name}"))
        await conn.execute(text(f"CREATE DATABASE {scratch_name}"))

    try:
        cfg = _cfg(scratch_url)
        for step, rev in (("upgrade", "head"), ("downgrade", "base"),
                          ("upgrade", "head"), ("downgrade", "base"),
                          ("upgrade", "head")):
            await asyncio.to_thread(getattr(command, step), cfg, rev)

        # After a full round trip the schema must match the models exactly.
        # Derived from metadata, not hardcoded — otherwise this rots every milestone.
        expected_tables = set(Base.metadata.tables) | {"alembic_version"}
        expected_enums = {
            c.type.name
            for t in Base.metadata.tables.values()
            for c in t.columns
            if isinstance(c.type, SAEnum) and c.type.name
        }

        eng = create_async_engine(scratch_url)
        async with eng.connect() as conn:
            tables = {r[0] for r in (await conn.execute(text(
                "select tablename from pg_tables where schemaname='public'")))}
            enums = {r[0] for r in (await conn.execute(text(
                "select typname from pg_type where typtype='e'")))}
        await eng.dispose()

        assert tables == expected_tables, f"table drift: {tables ^ expected_tables}"
        assert enums == expected_enums, (
            f"enum drift after round trip: {enums ^ expected_enums} — the downgrade "
            "probably does not DROP TYPE for a newly added enum"
        )
    finally:
        os.environ["ALEMBIC_DATABASE_URL"] = base
        async with admin.connect() as conn:
            await conn.execute(text(f"DROP DATABASE IF EXISTS {scratch_name}"))
        await admin.dispose()
