/**
 * GENERATED FILE — DO NOT EDIT.
 *
 * Produced from the API's OpenAPI document by:
 *   pnpm --filter @volt/api-types generate
 *
 * CI regenerates this and fails the build if it differs (D3b). A hand-edit here
 * is drift with extra steps: change the Pydantic schema instead.
 */

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_v1_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Profile */
        patch: operations["patch_profile_v1_profile_patch"];
        trace?: never;
    };
    "/v1/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Goals */
        get: operations["list_goals_v1_goals_get"];
        put?: never;
        /** Create Goal */
        post: operations["create_goal_v1_goals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/goals/{goal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Goal */
        get: operations["get_goal_v1_goals__goal_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Goal */
        patch: operations["patch_goal_v1_goals__goal_id__patch"];
        trace?: never;
    };
    "/v1/muscle-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Muscle Groups */
        get: operations["list_muscle_groups_v1_muscle_groups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exercises */
        get: operations["list_exercises_v1_exercises_get"];
        put?: never;
        /** Create Exercise */
        post: operations["create_exercise_v1_exercises_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exercises/{exercise_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exercise */
        get: operations["get_exercise_v1_exercises__exercise_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Exercise */
        patch: operations["patch_exercise_v1_exercises__exercise_id__patch"];
        trace?: never;
    };
    "/v1/exercises/{exercise_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive Exercise
         * @description Soft delete. History and analytics keep resolving; the exercise leaves pickers.
         */
        post: operations["archive_exercise_v1_exercises__exercise_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workout-programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Programs */
        get: operations["list_programs_v1_workout_programs_get"];
        put?: never;
        /** Create Program */
        post: operations["create_program_v1_workout_programs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workout-programs/{program_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Program */
        get: operations["get_program_v1_workout_programs__program_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Program
         * @description Hard delete, and ONLY when nothing references it. A program used by any
         *     session must be archived instead — BRD §7 soft-delete principle.
         */
        delete: operations["delete_program_v1_workout_programs__program_id__delete"];
        options?: never;
        head?: never;
        /** Patch Program */
        patch: operations["patch_program_v1_workout_programs__program_id__patch"];
        trace?: never;
    };
    "/v1/workout-programs/{program_id}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Duplicate Program
         * @description Deep copy. Every day and prescription gets a NEW id, so later edits to the
         *     copy cannot reach back into the original.
         */
        post: operations["duplicate_program_v1_workout_programs__program_id__duplicate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workout-programs/{program_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Program */
        post: operations["archive_program_v1_workout_programs__program_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workout-programs/{program_id}/days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Day */
        post: operations["create_day_v1_workout_programs__program_id__days_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/plan-days/{day_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Day
         * @description Allowed even when sessions used it — those sessions are self-describing and
         *     keep their records; plan_day_id simply becomes NULL.
         */
        delete: operations["delete_day_v1_plan_days__day_id__delete"];
        options?: never;
        head?: never;
        /** Patch Day */
        patch: operations["patch_day_v1_plan_days__day_id__patch"];
        trace?: never;
    };
    "/v1/plan-days/{day_id}/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Day Exercises
         * @description Bulk replace + reorder in ONE transaction, so an ordering change can never
         *     half-apply. order_index is assigned from list position — dense and 0-based.
         */
        put: operations["set_day_exercises_v1_plan_days__day_id__exercises_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workout-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description Cancelled sessions never appear — 4.7.
         */
        get: operations["list_sessions_v1_workout_sessions_get"];
        put?: never;
        /**
         * Start Session
         * @description 4.1 — start from a plan day, a repeat of an earlier session, an ad-hoc list,
         *     or nothing at all. Backdating is allowed (T9); the future is not.
         */
        post: operations["start_session_v1_workout_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workout-sessions/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Active
         * @description 4.2 — the logger asks this on every cold start. `null` is a valid answer, not
         *     a 404: "no workout in progress" is a normal state, not an error.
         */
        get: operations["get_active_v1_workout_sessions_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workout-sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_v1_workout_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workout-sessions/{session_id}/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Exercise
         * @description Adding an exercise mid-session is the common case, not an edge case.
         */
        post: operations["add_exercise_v1_workout_sessions__session_id__exercises_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/session-exercises/{se_id}/sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Set
         * @description 4.3 — `Idempotency-Key` is MANDATORY. Without it a dropped response makes the
         *     client choose between a lost set and a duplicated one, and it will guess wrong.
         */
        post: operations["add_set_v1_session_exercises__se_id__sets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workout-sessions/{session_id}/sets/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Flush Sets
         * @description 4.5 — the offline outbox flush. Idempotent PER SET, so a partially-delivered
         *     batch can be resent whole. Each item is {session_exercise_id, ...SetIn}.
         */
        post: operations["flush_sets_v1_workout_sessions__session_id__sets_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workout-sets/{set_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Set
         * @description 4.4 — delete and re-densify in ONE transaction. A gap in set_index would show
         *     as "Set 1, Set 3" in the logger.
         */
        delete: operations["delete_set_v1_workout_sets__set_id__delete"];
        options?: never;
        head?: never;
        /**
         * Patch Set
         * @description 4.4 — editing re-derives e1RM from the new numbers in the same transaction, so
         *     the row is never briefly inconsistent with its own values.
         */
        patch: operations["patch_set_v1_workout_sets__set_id__patch"];
        trace?: never;
    };
    "/v1/workout-sessions/{session_id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finish
         * @description 4.6 — volume, e1RM and PR evaluation run INSIDE this transaction, so the
         *     summary screen the user lands on is already correct.
         */
        post: operations["finish_v1_workout_sessions__session_id__finish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workout-sessions/{session_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel
         * @description 4.7 — the rows are RETAINED. Discarding is about the session leaving history
         *     and analytics, not about destroying what the user typed.
         */
        post: operations["cancel_v1_workout_sessions__session_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workout-sessions/{session_id}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reopen
         * @description W06.6 — "I forgot the last set". Refused while another session is open, so the
         *     partial unique index can never be violated.
         */
        post: operations["reopen_v1_workout_sessions__session_id__reopen_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exercises/{exercise_id}/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Exercise Records
         * @description The four records the app shows on E-11 and G-04.
         *
         *     `volume` is the best SINGLE SESSION, not a lifetime total — a number that only
         *     ever rises is not a record. See services.sessions.recompute_records_for_exercise.
         */
        get: operations["exercise_records_v1_exercises__exercise_id__records_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exercises/{exercise_id}/previous-performance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Previous Performance
         * @description 4.8 — what the logger shows under the entry pad: "last time you did 60 × 8".
         *
         *     Resolves by PRD §7.2: most recent COMPLETED session of this user containing this
         *     exercise, ordered by completed_at desc. Cancelled and in-progress sessions are
         *     invisible here — comparing against a workout that was discarded is worse than
         *     showing nothing.
         */
        get: operations["previous_performance_v1_exercises__exercise_id__previous_performance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuthOut
         * @description Register and login return the new user alongside a fresh token pair.
         */
        AuthOut: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default Bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
            user: components["schemas"]["UserRefOut"];
        };
        /**
         * DeletedOut
         * @description Every delete answers the same way, so the client has one shape to handle.
         */
        DeletedOut: {
            /** Deleted */
            deleted: boolean;
        };
        /** Envelope[AuthOut] */
        Envelope_AuthOut_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["AuthOut"] | null;
            error?: components["schemas"]["ErrorOut"] | null;
        };
        /** Envelope[DeletedOut] */
        Envelope_DeletedOut_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["DeletedOut"] | null;
            error?: components["schemas"]["ErrorOut"] | null;
        };
        /** Envelope[ExerciseOut] */
        Envelope_ExerciseOut_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["ExerciseOut"] | null;
            error?: components["schemas"]["ErrorOut"] | null;
        };
        /** Envelope[GoalOut] */
        Envelope_GoalOut_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["GoalOut"] | null;
            error?: components["schemas"]["ErrorOut"] | null;
        };
        /** Envelope[MeOut] */
        Envelope_MeOut_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["MeOut"] | null;
            error?: components["schemas"]["ErrorOut"] | null;
        };
        /** Envelope[PreviousPerformanceOut] */
        Envelope_PreviousPerformanceOut_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["PreviousPerformanceOut"] | null;
            error?: components["schemas"]["ErrorOut"] | null;
        };
        /** Envelope[ProfileOut] */
        Envelope_ProfileOut_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["ProfileOut"] | null;
            error?: components["schemas"]["ErrorOut"] | null;
        };
        /** Envelope[ProgramOut] */
        Envelope_ProgramOut_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["ProgramOut"] | null;
            error?: components["schemas"]["ErrorOut"] | null;
        };
        /** Envelope[SessionFinishOut] */
        Envelope_SessionFinishOut_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["SessionFinishOut"] | null;
            error?: components["schemas"]["ErrorOut"] | null;
        };
        /** Envelope[SessionOut] */
        Envelope_SessionOut_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["SessionOut"] | null;
            error?: components["schemas"]["ErrorOut"] | null;
        };
        /** Envelope[SetOut] */
        Envelope_SetOut_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["SetOut"] | null;
            error?: components["schemas"]["ErrorOut"] | null;
        };
        /** Envelope[SignedOutOut] */
        Envelope_SignedOutOut_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["SignedOutOut"] | null;
            error?: components["schemas"]["ErrorOut"] | null;
        };
        /** Envelope[TokenPair] */
        Envelope_TokenPair_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["TokenPair"] | null;
            error?: components["schemas"]["ErrorOut"] | null;
        };
        /** Envelope[dict[str, RecordEntryOut]] */
        Envelope_dict_str__RecordEntryOut__: {
            /** Success */
            success: boolean;
            /** Data */
            data?: {
                [key: string]: components["schemas"]["RecordEntryOut"];
            } | null;
            error?: components["schemas"]["ErrorOut"] | null;
        };
        /** Envelope[list[MuscleGroupOut]] */
        Envelope_list_MuscleGroupOut__: {
            /** Success */
            success: boolean;
            /** Data */
            data?: components["schemas"]["MuscleGroupOut"][] | null;
            error?: components["schemas"]["ErrorOut"] | null;
        };
        /**
         * ErrorOut
         * @description Always present on a failure, never on a success.
         */
        ErrorOut: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Fields */
            fields?: {
                [key: string]: string;
            };
            /** Request Id */
            request_id: string;
        };
        /** ExerciseIn */
        ExerciseIn: {
            /** Name */
            name: string;
            /**
             * Equipment
             * @default other
             * @enum {string}
             */
            equipment: "barbell" | "dumbbell" | "machine" | "cable" | "bodyweight" | "band" | "kettlebell" | "other";
            /** Movement Pattern */
            movement_pattern?: string | null;
            /** Aliases */
            aliases?: string[];
            /** Muscles */
            muscles: components["schemas"]["MuscleAssignmentIn"][];
            /**
             * Tracks Load
             * @default true
             */
            tracks_load: boolean;
            /**
             * Tracks Reps
             * @default true
             */
            tracks_reps: boolean;
            /**
             * Tracks Duration
             * @default false
             */
            tracks_duration: boolean;
            /**
             * Tracks Distance
             * @default false
             */
            tracks_distance: boolean;
            /**
             * Default Unit
             * @default kg
             */
            default_unit: string;
        };
        /** ExerciseOut */
        ExerciseOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Equipment
             * @enum {string}
             */
            equipment: "barbell" | "dumbbell" | "machine" | "cable" | "bodyweight" | "band" | "kettlebell" | "other";
            /** Movement Pattern */
            movement_pattern: string | null;
            /** Aliases */
            aliases: string[];
            /** Is Custom */
            is_custom: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "archived";
            /** Tracks Load */
            tracks_load: boolean;
            /** Tracks Reps */
            tracks_reps: boolean;
            /** Tracks Duration */
            tracks_duration: boolean;
            /** Tracks Distance */
            tracks_distance: boolean;
            /** Default Unit */
            default_unit: string;
            /**
             * Muscles
             * @default []
             */
            muscles: components["schemas"]["MuscleRefOut"][];
        };
        /** ExercisePatch */
        ExercisePatch: {
            /** Name */
            name?: string | null;
            /** Equipment */
            equipment?: ("barbell" | "dumbbell" | "machine" | "cable" | "bodyweight" | "band" | "kettlebell" | "other") | null;
            /** Movement Pattern */
            movement_pattern?: string | null;
            /** Aliases */
            aliases?: string[] | null;
            /** Muscles */
            muscles?: components["schemas"]["MuscleAssignmentIn"][] | null;
            /** Tracks Load */
            tracks_load?: boolean | null;
            /** Tracks Reps */
            tracks_reps?: boolean | null;
            /** Tracks Duration */
            tracks_duration?: boolean | null;
            /** Tracks Distance */
            tracks_distance?: boolean | null;
            /** Default Unit */
            default_unit?: string | null;
        };
        /** GoalIn */
        GoalIn: {
            /**
             * Goal Type
             * @enum {string}
             */
            goal_type: "fat_loss" | "muscle_gain" | "maintenance" | "strength" | "custom";
            /**
             * Metric Key
             * @default body_weight
             */
            metric_key: string;
            /**
             * Direction
             * @default down
             * @enum {string}
             */
            direction: "up" | "down" | "hold";
            /** Start Value */
            start_value?: number | null;
            /** Target Value */
            target_value: number;
            /**
             * Target Unit
             * @default kg
             */
            target_unit: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** Target Date */
            target_date?: string | null;
        };
        /** GoalOut */
        GoalOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Goal Type
             * @enum {string}
             */
            goal_type: "fat_loss" | "muscle_gain" | "maintenance" | "strength" | "custom";
            /** Metric Key */
            metric_key: string;
            /** Direction */
            direction: string;
            /** Start Value */
            start_value: number | null;
            /** Target Value */
            target_value: number;
            /** Target Unit */
            target_unit: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** Target Date */
            target_date: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "completed" | "paused";
        };
        /** GoalPatch */
        GoalPatch: {
            /** Target Value */
            target_value?: number | null;
            /** Target Date */
            target_date?: string | null;
            /** Status */
            status?: ("active" | "completed" | "paused") | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginIn */
        LoginIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MeOut */
        MeOut: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Status */
            status: string;
        };
        /**
         * Meta
         * @description Counters `ok(..., meta=...)` attaches. Which keys appear is per-endpoint:
         *
         *     * `total` — goal and program lists
         *     * `count` — session list
         *     * `limit` / `offset` / `count` — the exercise catalog
         *     * `accepted` — the outbox flush
         */
        Meta: {
            /** Total */
            total?: number | null;
            /** Count */
            count?: number | null;
            /** Limit */
            limit?: number | null;
            /** Offset */
            offset?: number | null;
            /** Accepted */
            accepted?: number | null;
        };
        /** MuscleAssignmentIn */
        MuscleAssignmentIn: {
            /**
             * Muscle Group Id
             * Format: uuid
             */
            muscle_group_id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "primary" | "secondary";
        };
        /** MuscleGroupOut */
        MuscleGroupOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Parent Id */
            parent_id: string | null;
            /** Sort Order */
            sort_order: number;
        };
        /** MuscleRefOut */
        MuscleRefOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "primary" | "secondary";
        };
        /** PagedEnvelope[SetBatchOut] */
        PagedEnvelope_SetBatchOut_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["SetBatchOut"] | null;
            error?: components["schemas"]["ErrorOut"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** PagedEnvelope[list[ExerciseOut]] */
        PagedEnvelope_list_ExerciseOut__: {
            /** Success */
            success: boolean;
            /** Data */
            data?: components["schemas"]["ExerciseOut"][] | null;
            error?: components["schemas"]["ErrorOut"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** PagedEnvelope[list[GoalOut]] */
        PagedEnvelope_list_GoalOut__: {
            /** Success */
            success: boolean;
            /** Data */
            data?: components["schemas"]["GoalOut"][] | null;
            error?: components["schemas"]["ErrorOut"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** PagedEnvelope[list[ProgramOut]] */
        PagedEnvelope_list_ProgramOut__: {
            /** Success */
            success: boolean;
            /** Data */
            data?: components["schemas"]["ProgramOut"][] | null;
            error?: components["schemas"]["ErrorOut"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** PagedEnvelope[list[SessionOut]] */
        PagedEnvelope_list_SessionOut__: {
            /** Success */
            success: boolean;
            /** Data */
            data?: components["schemas"]["SessionOut"][] | null;
            error?: components["schemas"]["ErrorOut"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** PersonalRecordOut */
        PersonalRecordOut: {
            /**
             * Exercise Id
             * Format: uuid
             */
            exercise_id: string;
            /** Exercise Name */
            exercise_name?: string | null;
            /**
             * Record Type
             * @enum {string}
             */
            record_type: "max_load" | "max_reps" | "volume" | "estimated_1rm";
            /** Value */
            value: number;
            /** Unit */
            unit: string;
            /** Previous Value */
            previous_value?: number | null;
        };
        /** PlanDayIn */
        PlanDayIn: {
            /** Name */
            name: string;
            /** Scheduled Weekday */
            scheduled_weekday?: number | null;
            /** Notes */
            notes?: string | null;
        };
        /** PlanDayOut */
        PlanDayOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Day Index */
            day_index: number;
            /** Name */
            name: string;
            /** Scheduled Weekday */
            scheduled_weekday: number | null;
            /** Notes */
            notes: string | null;
            /**
             * Exercises
             * @default []
             */
            exercises: components["schemas"]["PlanExerciseOut"][];
        };
        /** PlanDayPatch */
        PlanDayPatch: {
            /** Name */
            name?: string | null;
            /** Scheduled Weekday */
            scheduled_weekday?: number | null;
            /** Notes */
            notes?: string | null;
            /**
             * Clear Schedule
             * @default false
             */
            clear_schedule: boolean;
        };
        /** PlanExerciseIn */
        PlanExerciseIn: {
            /**
             * Exercise Id
             * Format: uuid
             */
            exercise_id: string;
            /** Target Sets */
            target_sets?: number | null;
            /** Target Reps Min */
            target_reps_min?: number | null;
            /** Target Reps Max */
            target_reps_max?: number | null;
            /** Target Load */
            target_load?: number | null;
            /**
             * Load Unit
             * @default kg
             * @enum {string}
             */
            load_unit: "kg" | "lb";
            /** Rest Seconds */
            rest_seconds?: number | null;
        };
        /** PlanExerciseOut */
        PlanExerciseOut: {
            /**
             * Exercise Id
             * Format: uuid
             */
            exercise_id: string;
            /** Target Sets */
            target_sets?: number | null;
            /** Target Reps Min */
            target_reps_min?: number | null;
            /** Target Reps Max */
            target_reps_max?: number | null;
            /** Target Load */
            target_load?: number | null;
            /**
             * Load Unit
             * @default kg
             * @enum {string}
             */
            load_unit: "kg" | "lb";
            /** Rest Seconds */
            rest_seconds?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Order Index */
            order_index: number;
            /** Exercise Name */
            exercise_name?: string | null;
        };
        /**
         * PreviousPerformanceOut
         * @description `data` is null when the exercise has never been performed — a first-time
         *     state the logger renders as a prompt, not an error.
         */
        PreviousPerformanceOut: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Local Date
             * Format: date
             */
            local_date: string;
            /** Completed At */
            completed_at?: string | null;
            /** Target Snapshot */
            target_snapshot?: {
                [key: string]: unknown;
            } | null;
            /** Best E1Rm Kg */
            best_e1rm_kg?: number | null;
            /**
             * Sets
             * @default []
             */
            sets: components["schemas"]["SetOut"][];
        };
        /** ProfileOut */
        ProfileOut: {
            /** Display Name */
            display_name?: string | null;
            /** Height Cm */
            height_cm?: number | null;
            /** Birth Date */
            birth_date?: string | null;
            /** Sex */
            sex?: string | null;
            /**
             * Preferred Unit System
             * @enum {string}
             */
            preferred_unit_system: "metric" | "imperial";
            /** Timezone */
            timezone: string;
            /** Week Starts On */
            week_starts_on: number;
            /**
             * Activity Level
             * @enum {string}
             */
            activity_level: "sedentary" | "light" | "moderate" | "very" | "extra";
            /** Daily Calorie Target */
            daily_calorie_target?: number | null;
            /** Protein G Target */
            protein_g_target?: number | null;
            /** Carbs G Target */
            carbs_g_target?: number | null;
            /** Fat G Target */
            fat_g_target?: number | null;
            /** Onboarding Completed */
            onboarding_completed: boolean;
        };
        /**
         * ProfilePatch
         * @description Every field optional — PATCH applies only what is sent.
         */
        ProfilePatch: {
            /** Display Name */
            display_name?: string | null;
            /** Height Cm */
            height_cm?: number | null;
            /** Birth Date */
            birth_date?: string | null;
            /** Sex */
            sex?: string | null;
            /** Preferred Unit System */
            preferred_unit_system?: ("metric" | "imperial") | null;
            /** Timezone */
            timezone?: string | null;
            /** Week Starts On */
            week_starts_on?: (0 | 1 | 6) | null;
            /** Activity Level */
            activity_level?: ("sedentary" | "light" | "moderate" | "very" | "extra") | null;
            /** Daily Calorie Target */
            daily_calorie_target?: number | null;
            /** Protein G Target */
            protein_g_target?: number | null;
            /** Carbs G Target */
            carbs_g_target?: number | null;
            /** Fat G Target */
            fat_g_target?: number | null;
            /** Onboarding Completed */
            onboarding_completed?: boolean | null;
        };
        /** ProgramIn */
        ProgramIn: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** ProgramOut */
        ProgramOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "archived";
            /**
             * Days
             * @default []
             */
            days: components["schemas"]["PlanDayOut"][];
        };
        /** ProgramPatch */
        ProgramPatch: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
        };
        /**
         * RecordEntryOut
         * @description One entry of `GET /exercises/{id}/records`, keyed by record type.
         */
        RecordEntryOut: {
            /** Value */
            value: number;
            /** Unit */
            unit: string;
            /**
             * Achieved At
             * Format: date-time
             */
            achieved_at: string;
        };
        /** RefreshIn */
        RefreshIn: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RegisterIn */
        RegisterIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Display Name */
            display_name?: string | null;
        };
        /** SessionExerciseIn */
        SessionExerciseIn: {
            /**
             * Exercise Id
             * Format: uuid
             */
            exercise_id: string;
            /** Position */
            position?: number | null;
        };
        /** SessionExerciseOut */
        SessionExerciseOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Exercise Id
             * Format: uuid
             */
            exercise_id: string;
            /** Exercise Name */
            exercise_name?: string | null;
            /** Order Index */
            order_index: number;
            /** Notes */
            notes: string | null;
            /** Skipped */
            skipped: boolean;
            /** Target Snapshot */
            target_snapshot: {
                [key: string]: unknown;
            } | null;
            /**
             * Sets
             * @default []
             */
            sets: components["schemas"]["SetOut"][];
        };
        /**
         * SessionFinishOut
         * @description Finish returns the session plus whatever records it improved (E-11).
         */
        SessionFinishOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Plan Day Id */
            plan_day_id: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "planned" | "in_progress" | "completed" | "cancelled";
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Completed At */
            completed_at: string | null;
            /**
             * Local Date
             * Format: date
             */
            local_date: string;
            /** Logged Timezone */
            logged_timezone: string;
            /** Notes */
            notes: string | null;
            /** Total Volume Kg */
            total_volume_kg: number | null;
            /** Duration Seconds */
            duration_seconds: number | null;
            /**
             * Exercises
             * @default []
             */
            exercises: components["schemas"]["SessionExerciseOut"][];
            /**
             * Records
             * @default []
             */
            records: components["schemas"]["PersonalRecordOut"][];
        };
        /** SessionOut */
        SessionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Plan Day Id */
            plan_day_id: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "planned" | "in_progress" | "completed" | "cancelled";
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Completed At */
            completed_at: string | null;
            /**
             * Local Date
             * Format: date
             */
            local_date: string;
            /** Logged Timezone */
            logged_timezone: string;
            /** Notes */
            notes: string | null;
            /** Total Volume Kg */
            total_volume_kg: number | null;
            /** Duration Seconds */
            duration_seconds: number | null;
            /**
             * Exercises
             * @default []
             */
            exercises: components["schemas"]["SessionExerciseOut"][];
        };
        /**
         * SessionStart
         * @description Exactly one source. `plan_day_id` snapshots the prescription at start.
         */
        SessionStart: {
            /** Plan Day Id */
            plan_day_id?: string | null;
            /** Repeat Session Id */
            repeat_session_id?: string | null;
            /** Exercise Ids */
            exercise_ids?: string[] | null;
            /** Started At */
            started_at?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * SetBatchItemOut
         * @description One outcome from the outbox flush. A malformed item fails alone.
         */
        SetBatchItemOut: {
            /** Client Id */
            client_id?: string | null;
            /** Accepted */
            accepted: boolean;
            /** Created */
            created?: boolean | null;
            set?: components["schemas"]["SetOut"] | null;
            /** Error */
            error?: string | null;
        };
        /** SetBatchOut */
        SetBatchOut: {
            /**
             * Results
             * @default []
             */
            results: components["schemas"]["SetBatchItemOut"][];
        };
        /** SetIn */
        SetIn: {
            /** Client Id */
            client_id?: string | null;
            /**
             * Set Type
             * @default working
             * @enum {string}
             */
            set_type: "warmup" | "working" | "drop" | "failure";
            /** Reps */
            reps?: number | null;
            /** Load Kg */
            load_kg?: number | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Distance M */
            distance_m?: number | null;
            /** Rpe */
            rpe?: number | null;
            /** Rir */
            rir?: number | null;
            /**
             * Load Unit Entered
             * @default kg
             * @enum {string}
             */
            load_unit_entered: "kg" | "lb";
            /**
             * Completed
             * @default true
             */
            completed: boolean;
            /** Performed At */
            performed_at?: string | null;
            /** Note */
            note?: string | null;
        };
        /** SetOut */
        SetOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Client Id */
            client_id: string | null;
            /** Set Index */
            set_index: number;
            /**
             * Set Type
             * @enum {string}
             */
            set_type: "warmup" | "working" | "drop" | "failure";
            /** Reps */
            reps: number | null;
            /** Load Kg */
            load_kg: number | null;
            /** Duration Seconds */
            duration_seconds: number | null;
            /** Distance M */
            distance_m: number | null;
            /** Rpe */
            rpe: number | null;
            /** Rir */
            rir: number | null;
            /** Completed */
            completed: boolean;
            /**
             * Performed At
             * Format: date-time
             */
            performed_at: string;
            /** Load Unit Entered */
            load_unit_entered: string;
            /** E1Rm Kg */
            e1rm_kg: number | null;
            /** Formula Version */
            formula_version: string | null;
            /** Is Pr */
            is_pr: boolean;
            /** Note */
            note: string | null;
        };
        /** SignedOutOut */
        SignedOutOut: {
            /** Signed Out */
            signed_out: boolean;
        };
        /** TokenPair */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default Bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /** UserRefOut */
        UserRefOut: {
            /** Id */
            id: string;
            /** Email */
            email: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    register_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_AuthOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_AuthOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_TokenPair_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SignedOutOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_MeOut_"];
                };
            };
        };
    };
    get_profile_v1_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ProfileOut_"];
                };
            };
        };
    };
    patch_profile_v1_profile_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfilePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ProfileOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_goals_v1_goals_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedEnvelope_list_GoalOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_goal_v1_goals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_GoalOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_goal_v1_goals__goal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_GoalOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_goal_v1_goals__goal_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_GoalOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_muscle_groups_v1_muscle_groups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_MuscleGroupOut__"];
                };
            };
        };
    };
    list_exercises_v1_exercises_get: {
        parameters: {
            query?: {
                q?: string | null;
                muscle?: string | null;
                equipment?: string | null;
                pattern?: string | null;
                mine?: boolean;
                include_archived?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedEnvelope_list_ExerciseOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_exercise_v1_exercises_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ExerciseOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exercise_v1_exercises__exercise_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ExerciseOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_exercise_v1_exercises__exercise_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExercisePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ExerciseOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_exercise_v1_exercises__exercise_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ExerciseOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_programs_v1_workout_programs_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedEnvelope_list_ProgramOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_program_v1_workout_programs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProgramIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ProgramOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_program_v1_workout_programs__program_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                program_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ProgramOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_program_v1_workout_programs__program_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                program_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_DeletedOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_program_v1_workout_programs__program_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                program_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProgramPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ProgramOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    duplicate_program_v1_workout_programs__program_id__duplicate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                program_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ProgramOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_program_v1_workout_programs__program_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                program_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ProgramOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_day_v1_workout_programs__program_id__days_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                program_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanDayIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ProgramOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_day_v1_plan_days__day_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                day_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ProgramOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_day_v1_plan_days__day_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                day_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanDayPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ProgramOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_day_exercises_v1_plan_days__day_id__exercises_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                day_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanExerciseIn"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ProgramOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_v1_workout_sessions_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedEnvelope_list_SessionOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_session_v1_workout_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionStart"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SessionOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_active_v1_workout_sessions_active_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SessionOut_"];
                };
            };
        };
    };
    get_session_v1_workout_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SessionOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_exercise_v1_workout_sessions__session_id__exercises_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionExerciseIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SessionOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_set_v1_session_exercises__se_id__sets_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                se_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SetOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    flush_sets_v1_workout_sessions__session_id__sets_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                }[];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedEnvelope_SetBatchOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_set_v1_workout_sets__set_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_DeletedOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_set_v1_workout_sets__set_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SetOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finish_v1_workout_sessions__session_id__finish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SessionFinishOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_v1_workout_sessions__session_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SessionOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reopen_v1_workout_sessions__session_id__reopen_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SessionOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    exercise_records_v1_exercises__exercise_id__records_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_dict_str__RecordEntryOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    previous_performance_v1_exercises__exercise_id__previous_performance_get: {
        parameters: {
            query?: {
                before?: string | null;
            };
            header?: never;
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_PreviousPerformanceOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
