"""m5 nutrition: foods, meals, meal items, categories, recipes

Revision ID: 2fb1377688cf
Revises: 9d3ed08759a8
Create Date: 2026-09-23 10:20:09.815595

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2fb1377688cf'
down_revision: str | Sequence[str] | None = '9d3ed08759a8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('calories', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('protein_g', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('carbs_g', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fat_g', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fiber_g', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('serving_grams', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('serving_label', sa.String(length=60), nullable=True),
    sa.Column('source', sa.Enum('internal', 'provider', 'user', name='food_source'), nullable=False),
    sa.Column('external_ref', sa.String(length=120), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_ref', name='uq_food_external_ref')
    )
    op.create_index('ix_foods_name', 'foods', ['name'], unique=False)
    op.create_index('ix_foods_owner', 'foods', ['owner_user_id'], unique=False)
    op.create_table('meals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('meal_type', sa.String(length=40), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('logged_timezone', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_id', name='uq_meal_client_id')
    )
    op.create_index('ix_meals_user_local_date', 'meals', ['user_id', 'local_date'], unique=False)
    op.create_table('meal_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meal_id', sa.UUID(), nullable=False),
    sa.Column('food_id', sa.UUID(), nullable=True),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('quantity_grams', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('calories', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('protein_g', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('carbs_g', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fat_g', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fiber_g', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('user_corrected', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('manual', 'text_ai', 'image_ai', name='item_source'), nullable=False),
    sa.Column('analysis_item_id', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meal_id', 'client_id', name='uq_meal_item_client_id')
    )
    op.create_index('ix_meal_items_confirmed', 'meal_items', ['meal_id'], unique=False, postgresql_where=sa.text('confirmed = true'))
    op.create_index('ix_meal_items_meal', 'meal_items', ['meal_id'], unique=False)
    op.create_table('meal_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('default_time', sa.Time(), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'slug', name='uq_meal_category_slug')
    )
    op.create_index('ix_meal_categories_user', 'meal_categories', ['user_id', 'sort_order'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('servings', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recipes_user', 'recipes', ['user_id', 'archived'], unique=False)
    op.create_table('recipe_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('food_id', sa.UUID(), nullable=True),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('quantity_grams', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('calories', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('protein_g', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('carbs_g', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fat_g', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recipe_items_recipe', 'recipe_items', ['recipe_id', 'sort_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recipe_items_recipe', table_name='recipe_items')
    op.drop_table('recipe_items')
    op.drop_index('ix_recipes_user', table_name='recipes')
    op.drop_table('recipes')
    op.drop_index('ix_meal_categories_user', table_name='meal_categories')
    op.drop_table('meal_categories')
    op.drop_index('ix_meal_items_meal', table_name='meal_items')
    op.drop_index('ix_meal_items_confirmed', table_name='meal_items', postgresql_where=sa.text('confirmed = true'))
    op.drop_table('meal_items')
    op.drop_index('ix_meals_user_local_date', table_name='meals')
    op.drop_table('meals')
    op.drop_index('ix_foods_owner', table_name='foods')
    op.drop_index('ix_foods_name', table_name='foods')
    op.drop_table('foods')
    # ### end Alembic commands ###

    # Postgres ENUM types are NOT dropped by drop_table. Without this the
    # downgrade leaves them behind and the next upgrade fails on "type already
    # exists" — which this project has already been bitten by once (m2), and
    # which only shows up when someone actually rolls back.
    for enum_name in ['food_source', 'item_source']:
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
