"""m6 ai food analyses, append-only

The tables are half of this migration. The other half is two triggers, and they
are the part that matters:

`food_analysis_items` rejects every UPDATE and every DELETE. AC-10 asserts that
a user's correction leaves the model's output byte-identical, and a guarantee
that depends on nobody ever writing the wrong statement is not a guarantee.

`food_analyses` is a job as well as a record, so its status may move forward
while its INPUT and the MODEL'S OUTPUT may not. `image_key` is excepted, because
BRD §18 lets a user delete their photographs without deleting the record of what
was analysed.


Revision ID: 4265ed56ff6a
Revises: 2fb1377688cf
Create Date: 2026-09-23 11:23:53.590151

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4265ed56ff6a'
down_revision: str | Sequence[str] | None = '2fb1377688cf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('input_type', sa.Enum('text', 'image', name='analysis_input_type'), nullable=False),
    sa.Column('source_text', sa.String(length=1000), nullable=True),
    sa.Column('image_key', sa.String(length=400), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='analysis_status'), nullable=False),
    sa.Column('error_code', sa.Enum('ai_unavailable', 'ai_invalid_output', 'image_unreadable', 'no_food_detected', 'quota_exceeded', name='analysis_error_code'), nullable=True),
    sa.Column('model_name', sa.String(length=120), nullable=True),
    sa.Column('schema_version', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_meal_id', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_meal_id'], ['meals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_id', name='uq_food_analysis_client_id')
    )
    op.create_index('ix_food_analyses_queue', 'food_analyses', ['status', 'created_at'], unique=False)
    op.create_index('ix_food_analyses_user', 'food_analyses', ['user_id', 'created_at'], unique=False)
    op.create_table('food_analysis_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('detected_name', sa.String(length=160), nullable=False),
    sa.Column('estimated_quantity', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('estimated_unit', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('proposed_calories', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('proposed_protein_g', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('proposed_carbs_g', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('proposed_fat_g', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('resolved_food_id', sa.UUID(), nullable=True),
    sa.Column('low_confidence', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['food_analyses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_food_id'], ['foods.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_food_analysis_items_analysis', 'food_analysis_items', ['analysis_id', 'order_index'], unique=False)
    # ### end Alembic commands ###

    # The FK G7 deferred: `meal_items.analysis_item_id` had nothing to point at
    # until now. RESTRICT because an analysis row is append-only and must never
    # be deleted out from under a meal that cites it.
    op.create_foreign_key(
        'fk_meal_items_analysis_item', 'meal_items', 'food_analysis_items',
        ['analysis_item_id'], ['id'], ondelete='RESTRICT',
    )

    # --- append-only, enforced where it cannot be argued with ---------------

    op.execute("""
        CREATE OR REPLACE FUNCTION food_analysis_items_append_only()
        RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION
                'food_analysis_items is append-only: % is not permitted', TG_OP
                USING ERRCODE = '23514';
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER food_analysis_items_no_update
        BEFORE UPDATE OR DELETE ON food_analysis_items
        FOR EACH ROW EXECUTE FUNCTION food_analysis_items_append_only();
    """)

    # The analysis row may change STATUS. It may not change what was asked or
    # what the model answered.
    op.execute("""
        CREATE OR REPLACE FUNCTION food_analyses_immutable_record()
        RETURNS trigger AS $$
        BEGIN
            -- What was asked is frozen from the moment it is asked.
            IF  NEW.user_id     IS DISTINCT FROM OLD.user_id
            OR  NEW.input_type  IS DISTINCT FROM OLD.input_type
            OR  NEW.source_text IS DISTINCT FROM OLD.source_text
            OR  NEW.created_at  IS DISTINCT FROM OLD.created_at
            THEN
                RAISE EXCEPTION
                    'food_analyses: the request is immutable'
                    USING ERRCODE = '23514';
            END IF;

            -- What the model answered is frozen once the job has ended.
            -- Guarding on "the column is already set" instead would leave a
            -- completed analysis that happened to have no notes open to having
            -- commentary invented for it afterwards.
            IF  OLD.status IN ('completed', 'failed')
            AND (NEW.status         IS DISTINCT FROM OLD.status
              OR NEW.model_name     IS DISTINCT FROM OLD.model_name
              OR NEW.schema_version IS DISTINCT FROM OLD.schema_version
              OR NEW.notes          IS DISTINCT FROM OLD.notes
              OR NEW.error_code     IS DISTINCT FROM OLD.error_code
              OR NEW.completed_at   IS DISTINCT FROM OLD.completed_at)
            THEN
                RAISE EXCEPTION
                    'food_analyses: the model output is immutable once the analysis has ended'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER food_analyses_immutable
        BEFORE UPDATE ON food_analyses
        FOR EACH ROW EXECUTE FUNCTION food_analyses_immutable_record();
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('fk_meal_items_analysis_item', 'meal_items', type_='foreignkey')
    op.execute("DROP TRIGGER IF EXISTS food_analyses_immutable ON food_analyses")
    op.execute("DROP FUNCTION IF EXISTS food_analyses_immutable_record()")
    op.execute("DROP TRIGGER IF EXISTS food_analysis_items_no_update ON food_analysis_items")
    op.execute("DROP FUNCTION IF EXISTS food_analysis_items_append_only()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_food_analysis_items_analysis', table_name='food_analysis_items')
    op.drop_table('food_analysis_items')
    op.drop_index('ix_food_analyses_user', table_name='food_analyses')
    op.drop_index('ix_food_analyses_queue', table_name='food_analyses')
    op.drop_table('food_analyses')
    # ### end Alembic commands ###

    # Postgres ENUM types survive drop_table. m2 and m5 were both bitten by
    # this; without these lines a downgrade leaves the types behind and the next
    # upgrade fails on "type already exists".
    for enum_name in ["analysis_input_type", "analysis_status", "analysis_error_code"]:
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
