"""m7 body metrics, daily summaries and progress photos

Two tables with opposite characters.

`body_metrics` is a record of measurements. There is deliberately **no unique
constraint per day** — Q5 makes the first weigh-in of a day canonical, and the
*read* enforces that. Refusing a second entry would be lying about what the user
actually did.

`daily_summaries` is a cache and nothing else. It carries no `updated_at`,
because it is never edited: it is deleted when anything under it moves and
rebuilt on the next read.


Revision ID: 75ffe22f7993
Revises: 4265ed56ff6a
Create Date: 2026-09-23 11:57:19.771071

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '75ffe22f7993'
down_revision: str | Sequence[str] | None = '4265ed56ff6a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('metric_key', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('logged_timezone', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_id', name='uq_body_metric_client_id')
    )
    op.create_index('ix_body_metrics_series', 'body_metrics', ['user_id', 'metric_key', 'local_date', 'measured_at'], unique=False)
    op.create_table('daily_summaries',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.Column('volume_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('calories', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('protein_g', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('carbs_g', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('fat_g', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('meals_logged', sa.Integer(), nullable=False),
    sa.Column('pending_count', sa.Integer(), nullable=False),
    sa.Column('incomplete', sa.Boolean(), nullable=False),
    sa.Column('body_weight_kg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'local_date')
    )
    op.create_index('ix_daily_summaries_user', 'daily_summaries', ['user_id', 'local_date'], unique=False)
    op.create_table('progress_photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('image_key', sa.String(length=400), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('pose', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_id', name='uq_progress_photo_client_id')
    )
    op.create_index('ix_progress_photos_user', 'progress_photos', ['user_id', 'local_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_progress_photos_user', table_name='progress_photos')
    op.drop_table('progress_photos')
    op.drop_index('ix_daily_summaries_user', table_name='daily_summaries')
    op.drop_table('daily_summaries')
    op.drop_index('ix_body_metrics_series', table_name='body_metrics')
    op.drop_table('body_metrics')
    # ### end Alembic commands ###
