"""m8 training profile, checkin interval and goal pace

Revision ID: 8c4f39a8ef79
Revises: 75ffe22f7993
Create Date: 2026-09-23 22:59:29.226586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c4f39a8ef79'
down_revision: Union[str, Sequence[str], None] = '75ffe22f7993'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fitness_goals', sa.Column('weekly_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('user_profiles', sa.Column('training_experience', sa.String(length=20), nullable=True))
    op.add_column('user_profiles', sa.Column('training_days_per_week', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('session_minutes', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('equipment', sa.String(length=20), nullable=True))
    op.add_column('user_profiles', sa.Column('checkin_interval_days', sa.Integer(), server_default='7', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'checkin_interval_days')
    op.drop_column('user_profiles', 'equipment')
    op.drop_column('user_profiles', 'session_minutes')
    op.drop_column('user_profiles', 'training_days_per_week')
    op.drop_column('user_profiles', 'training_experience')
    op.drop_column('fitness_goals', 'weekly_rate')
    # ### end Alembic commands ###
