"""m4 plan duration and distance targets

A prescription could only express sets x reps @ load, so a plank and a run had
nothing to prescribe. C-07 renders from `exercises.tracks_*`, and without these
two columns the timed and distance shapes had no target to write to — which would
have surfaced in G3 as a logger bug rather than a planning one.

Additive and nullable: existing rows are untouched and the downgrade is a clean
drop. Canonical units, as everywhere else: seconds and metres.


Revision ID: 9d3ed08759a8
Revises: b3c07d41f2a1
Create Date: 2026-09-22 13:25:47.277228

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9d3ed08759a8'
down_revision: str | Sequence[str] | None = 'b3c07d41f2a1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_exercises', sa.Column('target_duration_seconds', sa.Integer(), nullable=True))
    op.add_column('plan_exercises', sa.Column('target_distance_m', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan_exercises', 'target_distance_m')
    op.drop_column('plan_exercises', 'target_duration_seconds')
    # ### end Alembic commands ###
