"""m15 account tokens for recovery, verification and email change

One table for every single-use link the API emails: A-05's password reset,
A-06's address verification and K-02's email change. A row stores only the
SHA-256 of its token, as `refresh_tokens` does, so a leaked database holds no
working link. Nothing is backfilled: existing accounts simply have no link
outstanding, and `users.email_verified_at` (m1) already says who is verified.

Revision ID: cda78611d65c
Revises: c7e2a9d4f1b3
Create Date: 2026-09-26 15:53:55.634224

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cda78611d65c'
down_revision: str | Sequence[str] | None = 'c7e2a9d4f1b3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.Enum('password_reset', 'verify_email', 'change_email', name='account_token_purpose'), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_account_tokens_user_purpose', 'account_tokens', ['user_id', 'purpose'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_account_tokens_user_purpose', table_name='account_tokens')
    op.drop_table('account_tokens')
    # ### end Alembic commands ###

    # Postgres ENUM types survive drop_table (m2, m5 and m6 all say so): without
    # this the next upgrade fails on "type already exists".
    op.execute("DROP TYPE IF EXISTS account_token_purpose")
