"""m8 versioned calorie targets (Q8, G10)

A past day is judged against the targets it had. Existing users get one row
backfilled from their profile's current targets, effective from the day the
profile was created: the best record there is of what they were aiming at, and
exactly what every screen showed before this.

Revision ID: d204e60c092c
Revises: 8c4f39a8ef79
Create Date: 2026-09-24 11:45:29.063375

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd204e60c092c'
down_revision: str | Sequence[str] | None = '8c4f39a8ef79'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calorie_targets',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('protein_g', sa.Integer(), nullable=True),
    sa.Column('carbs_g', sa.Integer(), nullable=True),
    sa.Column('fat_g', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'effective_from')
    )
    # ### end Alembic commands ###
    op.execute("""
        INSERT INTO calorie_targets (user_id, effective_from, calories, protein_g, carbs_g, fat_g)
        SELECT user_id, (created_at AT TIME ZONE timezone)::date,
               daily_calorie_target, protein_g_target, carbs_g_target, fat_g_target
        FROM user_profiles
        WHERE daily_calorie_target IS NOT NULL OR protein_g_target IS NOT NULL
           OR carbs_g_target IS NOT NULL OR fat_g_target IS NOT NULL
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calorie_targets')
    # ### end Alembic commands ###
