"""The curated Indian dishes — how each one is valued, and where the number comes from.

Read by `scripts/import_usda.py`, which writes `app/seed/data/indian_foods.json`.
Edit here, re-run the import, commit both.

**Why not IFCT 2017?** The Indian Food Composition Tables (ICMR-NIN) are the
best source for Indian foods, but they are © NIN and published as a book; the
machine-readable copies online (e.g. the `ifct2017` npm/GitHub package, AGPL,
formerly MIT) are third-party transcriptions whose licence cannot grant rights
to NIN's data, and the Indian Nutrient Databank publishes no licence at all.
Neither may be redistributed in an app. So every figure here is traceable to a
public-domain USDA record instead, in one of three ways (`basis`):

- `fndds:<fdc id>` — the dish exists in USDA FNDDS 2021–2023, which has a
  surprising number of Indian dishes (dal, idli, dosa, biryani, samosa…).
  Its published per-100 g values are used as-is.
- `sr:<fdc id>` — a single SR Legacy food under its Indian name.
- `recipe` — calculated by FitLog from a standard home recipe (below, in
  grams) using SR Legacy values for each ingredient, divided by the cooked
  weight. This is how FNDDS and IFCT's own recipe tables are built; the recipe
  is the citation. Home cooking varies by ±20% or more (mostly the oil), so
  the output is rounded to whole kcal and one decimal of a gram — no more
  precision than a recipe can honestly claim.

Stated substitutions, because SR Legacy has no record for them: **paneer** is
valued as queso blanco (the same acid-set fresh whole-milk cheese); **poha**
(flattened rice) as raw white rice; **chana dal / kala chana** as chickpeas;
**jaggery** as brown sugar. Spices under ~1% of a dish's weight are omitted.

**Portions are household estimates**, the measures an Indian kitchen uses:
1 katori (small bowl) ≈ 150 g of dal, curry or sabzi; 1 plate of rice or
biryani ≈ 250 g; a roti ≈ 40 g. FNDDS's own portions are kept where it has
them. A portion is only a way to enter grams — the food stays per 100 g.
"""
from __future__ import annotations

from dataclasses import dataclass

# key -> (SR Legacy FDC id, the start of its description — checked at import,
# so a mistyped id fails loudly instead of valuing a dal with a biscuit)
INGREDIENTS: dict[str, tuple[int, str]] = {
    "atta": (168893, "Wheat flour, whole-grain"),
    "maida": (168894, "Wheat flour, white, all-purpose"),
    "sooji": (169715, "Semolina, enriched"),
    "besan": (174288, "Chickpea flour (besan)"),
    "rice_raw": (168877, "Rice, white, long-grain, regular, raw"),
    "rice_cooked": (168878, "Rice, white, long-grain, regular, enriched, cooked"),
    "toor_cooked": (172437, "Pigeon peas (red gram), mature seeds, cooked"),
    "moong_raw": (174256, "Mung beans, mature seeds, raw"),
    "moong_cooked": (174257, "Mung beans, mature seeds, cooked"),
    "masoor_cooked": (172421, "Lentils, mature seeds, cooked"),
    "chana_cooked": (173757, "Chickpeas (garbanzo beans, bengal gram), mature seeds, cooked"),
    "urad_raw": (174259, "Mungo beans, mature seeds, raw"),
    "urad_cooked": (172427, "Mungo beans, mature seeds, cooked"),
    "rajma_cooked": (175194, "Beans, kidney, red, mature seeds, cooked"),
    "lobia_cooked": (173759, "Cowpeas, common"),
    "potato_raw": (170026, "Potatoes, flesh and skin, raw"),
    "potato_boiled": (170440, "Potatoes, boiled, cooked without skin"),
    "onion": (170000, "Onions, raw"),
    "tomato": (170457, "Tomatoes, red, ripe, raw"),
    "peas": (170419, "Peas, green, raw"),
    "cauliflower": (169986, "Cauliflower, raw"),
    "okra": (169260, "Okra, raw"),
    "eggplant": (169228, "Eggplant, raw"),
    "spinach": (168462, "Spinach, raw"),
    "cabbage": (169975, "Cabbage, raw"),
    "bottle_gourd": (169232, "Gourd, white-flowered (calabash), raw"),
    "carrot": (170393, "Carrots, raw"),
    "green_beans": (169961, "Beans, snap, green, raw"),
    "mushroom": (169251, "Mushrooms, white, raw"),
    "capsicum": (170427, "Peppers, sweet, green, raw"),
    "mustard_greens": (169256, "Mustard greens, raw"),
    "cucumber": (168409, "Cucumber, with peel, raw"),
    "coriander": (169997, "Coriander (cilantro) leaves, raw"),
    "mint": (173475, "Spearmint, fresh"),
    "coconut": (170169, "Nuts, coconut meat, raw"),
    "coconut_milk": (170172, "Nuts, coconut milk, raw"),
    "ginger": (169231, "Ginger root, raw"),
    "garlic": (169230, "Garlic, raw"),
    "green_chilli": (170497, "Peppers, hot chili, green, raw"),
    "lemon_juice": (167747, "Lemon juice, raw"),
    "tamarind": (167763, "Tamarinds, raw"),
    "mango": (169910, "Mangos, raw"),
    "oil": (171017, "Oil, sunflower"),
    "mustard_oil": (172337, "Oil, mustard"),
    "ghee": (171314, "Butter, Clarified butter (ghee)"),
    "butter": (173410, "Butter, salted"),
    "cream": (170859, "Cream, fluid, heavy whipping"),
    "milk": (171265, "Milk, whole, 3.25% milkfat"),
    "milk_powder": (170876, "Milk, dry, whole"),
    "curd": (171284, "Yogurt, plain, whole milk"),
    "paneer": (172224, "Cheese, white, queso blanco"),
    "chicken": (171052, "Chicken, broilers or fryers, meat only, raw"),
    "goat": (175303, "Game meat, goat, raw"),
    "lamb_mince": (174370, "Lamb, ground, raw"),
    "fish": (175122, "Fish, mackerel, king, raw"),
    "prawns": (175179, "Crustaceans, shrimp, raw"),
    "egg": (171287, "Egg, whole, raw, fresh"),
    "egg_boiled": (173424, "Egg, whole, cooked, hard-boiled"),
    "sugar": (169655, "Sugars, granulated"),
    "jaggery": (168833, "Sugars, brown"),
    "cashew": (170162, "Nuts, cashew nuts, raw"),
    "peanuts": (172430, "Peanuts, all types, raw"),
    "almonds": (170567, "Nuts, almonds"),
    "sabudana": (169717, "Tapioca, pearl, dry"),
    "vermicelli": (169736, "Pasta, dry, enriched"),
    "pav": (172793, "Rolls, dinner, plain, commercially prepared"),
    "puffed_rice": (173912, "Cereals ready-to-eat, rice, puffed"),
    "makki_atta": (169697, "Cornmeal, whole-grain, yellow"),
    "bajra": (169702, "Millet, raw"),
    "jowar": (169716, "Sorghum grain"),
    "salt": (173468, "Salt, table"),
    "tea": (173227, "Beverages, tea, black, brewed"),
    "coffee": (171890, "Beverages, coffee, brewed, prepared with tap water"),
}

#: Where a stated substitute differs from the real ingredient in a way that
#: matters: queso blanco is salted and paneer/chhena is not, so the proxy's
#: sodium is dropped (the dish's own salt is listed separately in its recipe).
OVERRIDES: dict[str, dict[str, float]] = {
    "paneer": {"sodium_mg": 0.0},
}

KATORI = ("1 katori (small bowl)", 150.0)
KATORI_CURD = ("1 katori (small bowl)", 100.0)
PLATE = ("1 plate", 250.0)
GLASS = ("1 glass", 250.0)
CUP_CHAI = ("1 cup (chai cup)", 150.0)
TSP = ("1 tsp", 5.0)
TBSP = ("1 tbsp", 15.0)

Recipe = tuple[tuple[str, float], ...]


@dataclass(frozen=True, slots=True)
class Dish:
    slug: str
    name: str
    basis: str                                  # "fndds:<id>" | "sr:<id>" | "recipe"
    portions: tuple[tuple[str, float], ...]
    aliases: tuple[str, ...] = ()
    recipe: Recipe = ()
    yield_g: float | None = None                # cooked weight of `recipe`
    note: str = ""
    #: Search prior (see Food.search_weight). The dishes people log daily sit
    #: a little higher than the occasional ones.
    weight: int = 50


def fndds(slug, name, fdc_id, portions, aliases=(), note="", weight=50) -> Dish:
    return Dish(slug, name, f"fndds:{fdc_id}", tuple(portions), tuple(aliases),
                note=note, weight=weight)


def sr(slug, name, fdc_id, portions, aliases=(), note="", weight=50) -> Dish:
    return Dish(slug, name, f"sr:{fdc_id}", tuple(portions), tuple(aliases),
                note=note, weight=weight)


def recipe(slug, name, ingredients: Recipe, yield_g, portions, aliases=(), note="",
           weight=50) -> Dish:
    return Dish(slug, name, "recipe", tuple(portions), tuple(aliases),
                tuple(ingredients), yield_g, note, weight)


DISHES: tuple[Dish, ...] = (
    # ------------------------------------------------ FNDDS 2021-2023 records
    fndds("dal", "Dal (lentil curry)", 2707427, [KATORI, ("1 cup", 240)],
          ["dal", "daal", "dhal", "lentil dal"], weight=60),
    fndds("lentil-curry", "Lentil curry", 2707431, [KATORI, ("1 cup", 240)]),
    fndds("naan", "Naan", 2707613,
          [("1 medium naan", 90), ("1 piece (1/4 of 10 in naan)", 44), ("1 large naan (10 in)", 177)],
          ["nan", "plain naan", "garlic naan", "tandoori naan"], weight=55),
    fndds("paratha", "Paratha (plain)", 2707715, [("1 paratha", 70)],
          ["paratha", "parantha", "plain paratha", "lachha paratha"], weight=55),
    fndds("puri", "Puri", 2707714, [("1 puri", 36)], ["poori", "puris"]),
    fndds("chicken-biryani", "Chicken biryani", 2706538, [PLATE, ("1 cup", 196)],
          ["biryani", "biriyani", "chicken biriyani", "murgh biryani"], weight=55),
    fndds("mutton-biryani", "Mutton biryani", 2706490, [PLATE, ("1 cup", 196)],
          ["meat biryani", "gosht biryani", "lamb biryani"],
          note="FNDDS describes it as biryani with meat"),
    fndds("veg-biryani", "Vegetable biryani", 2708985, [PLATE, ("1 cup", 172)],
          ["veg biryani", "veg biriyani"]),
    fndds("idli", "Idli", 2708346, [("1 idli", 38)], ["idly", "idlis"], weight=55),
    fndds("plain-dosa", "Plain dosa", 2708347,
          [("1 medium dosa", 80), ("1 small dosa", 35), ("1 large dosa", 155)],
          ["dosa", "sada dosa", "dosai"], weight=55),
    fndds("masala-dosa", "Masala dosa", 2709129,
          [("1 medium masala dosa", 267), ("1 small masala dosa", 113)],
          ["dosa with potato filling"], weight=55),
    fndds("samosa", "Samosa", 2708730, [("1 samosa", 100), ("1 small samosa", 25)],
          ["aloo samosa", "samosas", "singara"]),
    fndds("palak-paneer", "Palak paneer", 2709631, [KATORI, ("1 cup", 200)], ["saag paneer"]),
    fndds("chicken-curry", "Chicken curry", 2706437, [KATORI, ("1 cup", 240)],
          ["murgh curry", "chicken gravy", "chicken masala curry"], weight=55),
    fndds("chicken-curry-rice", "Chicken curry with rice", 2706438, [PLATE],
          ["chicken curry rice"]),
    fndds("fish-curry", "Fish curry", 2706460, [KATORI, ("1 cup", 240)],
          ["machli curry", "meen curry", "macher jhol"]),
    fndds("veg-curry", "Vegetable curry", 2710067, [KATORI, ("1 cup", 240)],
          ["mixed vegetable curry", "veg curry", "sabzi", "subzi"]),
    fndds("pakora", "Pakora", 2710066, [("1 pakora", 12), ("1 plate (6 pieces)", 72)],
          ["pakoda", "bhajiya", "bhaji", "onion pakora", "pakodi"]),
    fndds("sweet-chutney", "Sweet chutney", 2709309, [TBSP],
          ["mango chutney", "saunth"], note="a sweet fruit chutney"),
    fndds("upma", "Upma", 2709128, [KATORI, ("1 cup", 170)], ["rava upma", "uppittu"]),
    fndds("sambar", "Sambar", 2707430, [KATORI, ("1 cup", 248)], ["sambhar"], weight=55),
    fndds("chana-saag", "Chana saag", 2709632, [KATORI, ("1 cup", 245)],
          ["channa saag", "chole saag"]),
    fndds("medu-vada", "Medu vada", 2709130, [("1 vada", 30)],
          ["vada", "vadai", "urad vada", "uzhunnu vada"]),
    fndds("papad", "Papad (roasted)", 2707429, [("1 papad", 9)],
          ["papadum", "poppadom", "appalam", "papad"]),
    fndds("barfi", "Barfi", 2705700, [("1 piece", 45), ("1 small piece", 25)],
          ["burfi", "milk barfi"]),
    fndds("ladoo", "Ladoo", 2710351, [("1 ladoo", 60), ("1 small ladoo", 30)],
          ["laddu", "laddoo"]),
    fndds("milk-tea", "Chai (milk tea, sweetened)", 2710506, [CUP_CHAI, ("1 mug", 240)],
          ["chai", "tea with milk", "masala chai", "cutting chai", "milk tea"], weight=55,
          note="FNDDS values include sugar"),
    fndds("khichdi", "Khichdi", 2709029, [KATORI, ("1 cup", 207)],
          ["khichri", "kitchari", "dal khichdi"],
          note="FNDDS describes it as white rice with lentils"),
    fndds("curd", "Curd (dahi), whole milk", 2705418, [KATORI_CURD, ("1 cup", 245)],
          ["curd", "dahi", "plain curd", "doi"], weight=60),
    fndds("veg-fried-rice", "Veg fried rice", 2708951, [PLATE, ("1 cup", 166)],
          ["fried rice", "vegetable fried rice"]),
    fndds("chicken-fried-rice", "Chicken fried rice", 2708953, [PLATE, ("1 cup", 198)]),
    fndds("hakka-noodles", "Veg hakka noodles", 2708799, [PLATE],
          ["hakka noodles", "veg noodles", "veg chowmein"],
          note="FNDDS describes it as meatless lo mein"),

    # ------------------------------------------------------ SR Legacy records
    sr("pav", "Pav (bread roll)", 172793, [("1 pav", 35)], ["pav", "ladi pav", "pao"],
       note="SR describes it as a plain dinner roll"),

    # ------------------------------------------------------------- flatbreads
    recipe("phulka", "Phulka (roti, no ghee)",
           [("atta", 100), ("water", 65)], 135, [("1 phulka", 30), ("1 roti", 40)],
           ["phulka", "fulka", "plain roti"]),
    recipe("ghee-roti", "Roti with ghee",
           [("atta", 100), ("water", 65), ("ghee", 10)], 145, [("1 roti", 42)],
           ["ghee roti", "chapati with ghee", "tawa roti"]),
    recipe("aloo-paratha", "Aloo paratha",
           [("atta", 200), ("water", 130), ("potato_boiled", 250), ("onion", 20),
            ("green_chilli", 5), ("salt", 5), ("ghee", 25)], 560, [("1 paratha", 110)],
           ["potato paratha", "aloo parantha"], weight=55),
    recipe("gobi-paratha", "Gobi paratha",
           [("atta", 200), ("water", 130), ("cauliflower", 200), ("green_chilli", 5),
            ("salt", 5), ("ghee", 25)], 510, [("1 paratha", 110)],
           ["cauliflower paratha", "gobhi paratha"]),
    recipe("paneer-paratha", "Paneer paratha",
           [("atta", 200), ("water", 130), ("paneer", 150), ("onion", 30),
            ("salt", 4), ("ghee", 25)], 500, [("1 paratha", 110)], ["paneer parantha"]),
    recipe("butter-naan", "Butter naan",
           [("maida", 250), ("curd", 60), ("milk", 40), ("water", 80), ("oil", 10),
            ("sugar", 5), ("salt", 4), ("butter", 20)], 400, [("1 naan", 100)]),
    recipe("bhatura", "Bhatura",
           [("maida", 250), ("curd", 60), ("water", 70), ("sugar", 5), ("salt", 3),
            ("oil", 50)], 378, [("1 bhatura", 70)], ["bhature", "batura"],
           note="deep-fried; oil taken up estimated at 45 g per 390 g dough"),
    recipe("missi-roti", "Missi roti",
           [("atta", 100), ("besan", 100), ("onion", 20), ("oil", 10), ("water", 120),
            ("salt", 3)], 285, [("1 roti", 50)]),
    recipe("makki-roti", "Makki ki roti",
           [("makki_atta", 200), ("water", 140), ("salt", 2), ("ghee", 10)], 290,
           [("1 roti", 60)], ["makki roti", "makki di roti", "corn roti"]),
    recipe("bajra-roti", "Bajra roti",
           [("bajra", 200), ("water", 150), ("salt", 2)], 290, [("1 roti", 50)],
           ["bajra bhakri", "bajre ki roti", "millet roti"]),
    recipe("jowar-roti", "Jowar roti",
           [("jowar", 200), ("water", 150), ("salt", 2)], 290, [("1 roti", 50)],
           ["jowar bhakri", "jolada rotti", "sorghum roti"]),
    recipe("uttapam", "Uttapam",
           [("rice_raw", 100), ("urad_raw", 35), ("water", 170), ("onion", 40),
            ("tomato", 30), ("oil", 15), ("salt", 3)], 335, [("1 uttapam", 120)],
           ["uthappam", "onion uttapam"]),
    recipe("besan-chilla", "Besan chilla",
           [("besan", 100), ("water", 120), ("onion", 30), ("tomato", 20), ("oil", 10),
            ("salt", 3)], 230, [("1 chilla", 70)], ["besan cheela", "besan pancake"]),
    recipe("moong-chilla", "Moong dal chilla",
           [("moong_raw", 100), ("water", 130), ("onion", 30), ("oil", 10), ("salt", 3)],
           220, [("1 chilla", 70)], ["moong cheela", "pesarattu"]),

    # ------------------------------------------------------------ rice dishes
    recipe("jeera-rice", "Jeera rice",
           [("rice_cooked", 600), ("ghee", 15), ("salt", 4)], 610, [PLATE, KATORI],
           ["cumin rice"]),
    recipe("veg-pulao", "Vegetable pulao",
           [("rice_cooked", 500), ("peas", 60), ("carrot", 50), ("onion", 50),
            ("green_beans", 40), ("oil", 20), ("salt", 5)], 690, [PLATE, KATORI],
           ["pulao", "pulav", "veg pulav", "pilaf"]),
    recipe("lemon-rice", "Lemon rice",
           [("rice_cooked", 500), ("oil", 20), ("peanuts", 25), ("lemon_juice", 20),
            ("salt", 5)], 560, [PLATE, KATORI], ["chitranna", "nimbu rice"]),
    recipe("curd-rice", "Curd rice",
           [("rice_cooked", 300), ("curd", 250), ("milk", 50), ("oil", 5), ("salt", 4)],
           600, [PLATE, KATORI], ["thayir sadam", "dahi chawal", "mosaranna"]),
    recipe("tamarind-rice", "Tamarind rice",
           [("rice_cooked", 500), ("tamarind", 25), ("oil", 30), ("peanuts", 20),
            ("jaggery", 10), ("salt", 6)], 580, [PLATE, KATORI],
           ["puliyogare", "puli sadam", "pulihora"]),
    recipe("coconut-rice", "Coconut rice",
           [("rice_cooked", 500), ("coconut", 60), ("oil", 15), ("salt", 4)], 575,
           [PLATE, KATORI], ["thengai sadam"]),
    recipe("ghee-rice", "Ghee rice",
           [("rice_cooked", 500), ("ghee", 25), ("onion", 30), ("cashew", 10),
            ("salt", 4)], 560, [PLATE, KATORI], ["neychoru"]),
    recipe("egg-fried-rice", "Egg fried rice",
           [("rice_cooked", 500), ("egg", 100), ("oil", 25), ("onion", 40),
            ("capsicum", 30), ("carrot", 30), ("salt", 5)], 700, [PLATE]),
    recipe("ven-pongal", "Ven pongal",
           [("rice_raw", 100), ("moong_raw", 50), ("water", 600), ("ghee", 25),
            ("cashew", 10), ("salt", 4)], 560, [KATORI, PLATE], ["pongal", "khara pongal"]),

    # ------------------------------------------------------- dals and legumes
    recipe("dal-tadka", "Dal tadka (toor dal)",
           [("toor_cooked", 400), ("water", 150), ("ghee", 15), ("onion", 30),
            ("tomato", 50), ("garlic", 5), ("green_chilli", 3), ("salt", 5)], 610,
           [KATORI], ["dal tadka", "toor dal", "arhar dal", "tuvar dal", "dal fry"],
           weight=60),
    recipe("moong-dal", "Moong dal",
           [("moong_cooked", 400), ("water", 150), ("ghee", 10), ("tomato", 40),
            ("onion", 20), ("salt", 5)], 580, [KATORI], ["yellow dal", "mung dal"]),
    recipe("masoor-dal", "Masoor dal",
           [("masoor_cooked", 400), ("water", 150), ("oil", 10), ("onion", 30),
            ("tomato", 50), ("salt", 5)], 600, [KATORI], ["red lentil dal", "masur dal"]),
    recipe("chana-dal", "Chana dal",
           [("chana_cooked", 400), ("water", 120), ("ghee", 15), ("onion", 30),
            ("tomato", 40), ("salt", 5)], 570, [KATORI], ["chana dal fry"],
           note="split bengal gram valued as SR chickpeas"),
    recipe("dal-makhani", "Dal makhani",
           [("urad_cooked", 300), ("rajma_cooked", 60), ("butter", 30), ("cream", 40),
            ("tomato", 100), ("onion", 40), ("ginger", 5), ("garlic", 5), ("salt", 6),
            ("water", 100)], 600, [KATORI], ["maa ki dal", "dal makhni"], weight=55),
    recipe("rajma", "Rajma masala",
           [("rajma_cooked", 400), ("onion", 80), ("tomato", 120), ("oil", 20),
            ("ginger", 5), ("garlic", 5), ("salt", 6), ("water", 100)], 660, [KATORI],
           ["rajma", "rajma curry", "kidney bean curry"], weight=55),
    recipe("chole", "Chole (chana masala)",
           [("chana_cooked", 400), ("onion", 80), ("tomato", 120), ("oil", 25),
            ("ginger", 5), ("garlic", 5), ("salt", 6), ("water", 80)], 650, [KATORI],
           ["chole", "chana masala", "chholay", "kabuli chana curry"], weight=55),
    recipe("kala-chana", "Kala chana curry",
           [("chana_cooked", 400), ("onion", 60), ("tomato", 100), ("oil", 20),
            ("salt", 6), ("water", 100)], 620, [KATORI], ["black chana curry"],
           note="black chickpeas valued as SR chickpeas"),
    recipe("lobia", "Lobia curry",
           [("lobia_cooked", 400), ("onion", 60), ("tomato", 100), ("oil", 20),
            ("salt", 5), ("water", 100)], 620, [KATORI], ["lobia", "chawli", "black eyed peas curry"]),
    recipe("kadhi", "Kadhi",
           [("curd", 300), ("besan", 40), ("water", 400), ("oil", 10), ("ghee", 5),
            ("salt", 5)], 610, [KATORI], ["kadi", "dahi kadhi"]),
    recipe("kadhi-pakora", "Kadhi pakora",
           [("curd", 300), ("besan", 100), ("water", 400), ("oil", 30), ("ghee", 5),
            ("onion", 40), ("salt", 6)], 720, [KATORI], ["kadhi pakoda"]),
    recipe("rasam", "Rasam",
           [("tomato", 200), ("tamarind", 15), ("toor_cooked", 60), ("water", 600),
            ("ghee", 5), ("salt", 6)], 780, [KATORI, ("1 cup", 240)], ["saaru", "chaaru"]),

    # ---------------------------------------------------------- sabzi / curry
    recipe("aloo-gobi", "Aloo gobi",
           [("potato_raw", 250), ("cauliflower", 300), ("onion", 50), ("tomato", 60),
            ("oil", 30), ("salt", 6)], 560, [KATORI], ["aloo gobhi"], weight=55),
    recipe("aloo-matar", "Aloo matar",
           [("potato_raw", 300), ("peas", 150), ("onion", 60), ("tomato", 120),
            ("oil", 25), ("salt", 6), ("water", 150)], 700, [KATORI], ["aloo mutter"]),
    recipe("jeera-aloo", "Jeera aloo",
           [("potato_boiled", 500), ("oil", 25), ("salt", 6)], 510, [KATORI],
           ["cumin potatoes"]),
    recipe("aloo-sabzi", "Aloo sabzi (potato curry)",
           [("potato_boiled", 400), ("tomato", 100), ("oil", 20), ("salt", 6),
            ("water", 200)], 650, [KATORI], ["aloo curry", "aloo ki sabzi", "potato sabzi"]),
    recipe("dum-aloo", "Dum aloo",
           [("potato_boiled", 400), ("curd", 100), ("oil", 35), ("onion", 60),
            ("tomato", 80), ("salt", 6), ("water", 100)], 650, [KATORI]),
    recipe("bhindi", "Bhindi masala",
           [("okra", 400), ("onion", 80), ("tomato", 50), ("oil", 35), ("salt", 5)],
           420, [KATORI], ["bhindi", "okra sabzi", "bhindi fry"]),
    recipe("baingan-bharta", "Baingan bharta",
           [("eggplant", 600), ("onion", 80), ("tomato", 100), ("oil", 25),
            ("garlic", 5), ("salt", 5)], 560, [KATORI], ["baingan ka bharta", "brinjal bharta"]),
    recipe("mixed-veg", "Mixed vegetable sabzi",
           [("potato_raw", 150), ("carrot", 100), ("peas", 100), ("green_beans", 100),
            ("cauliflower", 100), ("onion", 50), ("tomato", 80), ("oil", 25),
            ("salt", 6)], 600, [KATORI], ["mix veg", "mixed veg"]),
    recipe("lauki", "Lauki sabzi",
           [("bottle_gourd", 500), ("tomato", 60), ("onion", 40), ("oil", 15),
            ("salt", 5)], 480, [KATORI], ["lauki", "ghiya sabzi", "bottle gourd curry"]),
    recipe("cabbage-sabzi", "Cabbage sabzi",
           [("cabbage", 500), ("peas", 50), ("oil", 20), ("salt", 5)], 450, [KATORI],
           ["patta gobhi", "cabbage poriyal", "bandh gobhi"]),
    recipe("beans-poriyal", "Beans poriyal",
           [("green_beans", 400), ("coconut", 40), ("oil", 15), ("salt", 5)], 400,
           [KATORI], ["beans thoran", "beans sabzi"]),
    recipe("sarson-saag", "Sarson ka saag",
           [("mustard_greens", 500), ("spinach", 200), ("makki_atta", 20), ("ghee", 25),
            ("onion", 40), ("garlic", 10), ("green_chilli", 5), ("salt", 6),
            ("water", 100)], 600, [KATORI], ["saag", "sarson saag"]),
    recipe("avial", "Avial",
           [("carrot", 100), ("green_beans", 100), ("potato_raw", 100),
            ("bottle_gourd", 100), ("coconut", 80), ("curd", 60), ("oil", 15),
            ("salt", 5)], 500, [KATORI], ["aviyal"]),
    recipe("mushroom-masala", "Mushroom masala",
           [("mushroom", 400), ("onion", 80), ("tomato", 120), ("oil", 25), ("cream", 20),
            ("salt", 5)], 500, [KATORI], ["mushroom curry"]),
    recipe("matar-paneer", "Matar paneer",
           [("paneer", 200), ("peas", 150), ("onion", 80), ("tomato", 150), ("oil", 25),
            ("cream", 20), ("salt", 6), ("water", 150)], 700, [KATORI], ["mutter paneer"]),
    recipe("paneer-butter-masala", "Paneer butter masala",
           [("paneer", 250), ("tomato", 250), ("butter", 40), ("cream", 60), ("onion", 50),
            ("cashew", 20), ("sugar", 5), ("salt", 6), ("water", 100)], 680, [KATORI],
           ["paneer makhani"], weight=55),
    recipe("kadai-paneer", "Kadai paneer",
           [("paneer", 250), ("capsicum", 120), ("onion", 100), ("tomato", 150),
            ("oil", 30), ("salt", 6)], 560, [KATORI], ["karahi paneer"]),
    recipe("shahi-paneer", "Shahi paneer",
           [("paneer", 250), ("cream", 80), ("cashew", 30), ("onion", 60), ("tomato", 120),
            ("butter", 20), ("curd", 50), ("salt", 6), ("water", 80)], 620, [KATORI]),
    recipe("paneer-bhurji", "Paneer bhurji",
           [("paneer", 250), ("onion", 60), ("tomato", 80), ("capsicum", 40), ("oil", 20),
            ("salt", 4)], 400, [KATORI], ["scrambled paneer"]),
    recipe("paneer-tikka", "Paneer tikka",
           [("paneer", 300), ("curd", 60), ("besan", 10), ("capsicum", 60), ("onion", 60),
            ("oil", 15), ("salt", 5)], 430, [("1 skewer (6 pieces)", 150), ("1 piece", 25)]),
    recipe("malai-kofta", "Malai kofta",
           [("paneer", 100), ("potato_boiled", 150), ("maida", 15), ("oil", 30),
            ("cream", 60), ("cashew", 25), ("onion", 60), ("tomato", 150), ("butter", 15),
            ("salt", 6), ("water", 100)], 620, [KATORI]),

    # ---------------------------------------------------------------- non-veg
    recipe("butter-chicken", "Butter chicken",
           [("chicken", 500), ("curd", 80), ("butter", 40), ("cream", 80), ("tomato", 300),
            ("cashew", 20), ("sugar", 8), ("ginger", 10), ("garlic", 10), ("salt", 8),
            ("oil", 10), ("water", 80)], 950, [KATORI], ["murgh makhani", "chicken makhani"],
           weight=55),
    recipe("chicken-tikka-masala", "Chicken tikka masala",
           [("chicken", 500), ("curd", 100), ("oil", 30), ("onion", 120), ("tomato", 250),
            ("cream", 60), ("ginger", 10), ("garlic", 10), ("salt", 8)], 900, [KATORI],
           ["tikka masala", "ctm"]),
    recipe("chicken-tikka", "Chicken tikka",
           [("chicken", 500), ("curd", 100), ("oil", 15), ("lemon_juice", 10),
            ("ginger", 10), ("garlic", 10), ("salt", 6)], 490,
           [("1 skewer (6 pieces)", 150), ("1 piece", 25)], ["murgh tikka"]),
    recipe("tandoori-chicken", "Tandoori chicken",
           [("chicken", 600), ("curd", 100), ("oil", 15), ("lemon_juice", 15), ("salt", 7)],
           550, [("1 leg piece (edible part)", 120), ("1 quarter (edible part)", 180)],
           note="per 100 g of meat eaten, bone excluded"),
    recipe("chicken-korma", "Chicken korma",
           [("chicken", 500), ("curd", 150), ("onion", 150), ("cashew", 30), ("ghee", 30),
            ("cream", 40), ("salt", 8), ("water", 100)], 850, [KATORI]),
    recipe("kadai-chicken", "Kadai chicken",
           [("chicken", 500), ("capsicum", 100), ("onion", 120), ("tomato", 200),
            ("oil", 35), ("salt", 8)], 800, [KATORI], ["karahi chicken"]),
    recipe("mutton-curry", "Mutton curry",
           [("goat", 500), ("onion", 150), ("tomato", 150), ("curd", 80), ("oil", 40),
            ("ginger", 10), ("garlic", 10), ("salt", 8), ("water", 300)], 900, [KATORI],
           ["mutton masala", "gosht curry", "rogan josh", "goat curry"],
           note="goat meat, boneless"),
    recipe("keema-matar", "Keema matar",
           [("lamb_mince", 400), ("peas", 150), ("onion", 100), ("tomato", 150),
            ("oil", 15), ("salt", 7)], 680, [KATORI], ["keema", "mutton keema"]),
    recipe("egg-curry", "Egg curry",
           [("egg_boiled", 300), ("onion", 120), ("tomato", 150), ("oil", 30), ("salt", 6),
            ("water", 150)], 650, [KATORI, ("1 egg with gravy", 110)],
           ["anda curry", "egg masala"]),
    recipe("egg-bhurji", "Egg bhurji",
           [("egg", 300), ("onion", 60), ("tomato", 60), ("oil", 15), ("green_chilli", 5),
            ("salt", 4)], 380, [KATORI, ("2-egg serving", 125)],
           ["anda bhurji", "masala scrambled eggs"]),
    recipe("masala-omelette", "Masala omelette",
           [("egg", 100), ("onion", 20), ("tomato", 15), ("green_chilli", 3), ("oil", 5),
            ("salt", 1)], 130, [("1 omelette (2 eggs)", 130)], ["masala omelet", "anda omelette"]),
    recipe("fish-fry", "Fish fry",
           [("fish", 500), ("besan", 20), ("oil", 40), ("lemon_juice", 10), ("salt", 6)],
           460, [("1 piece", 80)], ["tawa fish", "fried fish", "machli fry"],
           note="shallow-fried; king mackerel (surmai) as the fish"),
    recipe("fish-curry-coconut", "Fish curry (coconut)",
           [("fish", 400), ("coconut_milk", 250), ("onion", 60), ("tamarind", 10),
            ("oil", 20), ("salt", 6), ("water", 100)], 720, [KATORI],
           ["goan fish curry", "kerala fish curry", "meen moilee"]),
    recipe("prawn-curry", "Prawn curry",
           [("prawns", 400), ("coconut_milk", 200), ("onion", 80), ("tomato", 80),
            ("oil", 20), ("salt", 6)], 680, [KATORI], ["jhinga curry", "shrimp curry"]),

    # ------------------------------------------------ breakfast and snacks
    recipe("poha", "Poha",
           [("rice_raw", 150), ("water", 200), ("onion", 60), ("potato_raw", 60),
            ("peanuts", 20), ("oil", 15), ("lemon_juice", 10), ("sugar", 3), ("salt", 4)],
           500, [KATORI, PLATE], ["kanda poha", "aloo poha", "pohe"], weight=55,
           note="flattened rice valued as raw white rice"),
    recipe("dhokla", "Dhokla",
           [("besan", 100), ("curd", 60), ("water", 160), ("oil", 12), ("sugar", 8),
            ("lemon_juice", 10), ("salt", 3)], 340, [("1 piece", 30), ("1 plate (4 pieces)", 120)],
           ["khaman", "khaman dhokla"]),
    recipe("pav-bhaji", "Pav bhaji (bhaji only)",
           [("potato_boiled", 300), ("cauliflower", 100), ("peas", 80), ("capsicum", 60),
            ("tomato", 200), ("onion", 80), ("butter", 50), ("salt", 7), ("water", 100)],
           800, [KATORI], ["bhaji", "pav bhaji"]),
    recipe("vada-pav", "Vada pav",
           [("pav", 40), ("potato_boiled", 80), ("besan", 20), ("oil", 12), ("salt", 1)],
           150, [("1 vada pav", 150)], ["wada pav", "batata vada pav"]),
    recipe("aloo-tikki", "Aloo tikki",
           [("potato_boiled", 400), ("peas", 50), ("besan", 20), ("oil", 40), ("salt", 5)],
           460, [("1 tikki", 50)], ["aloo tikia", "potato patty"]),
    recipe("bhel-puri", "Bhel puri",
           [("puffed_rice", 60), ("onion", 30), ("tomato", 30), ("potato_boiled", 40),
            ("peanuts", 10), ("besan", 15), ("oil", 8), ("sugar", 8), ("tamarind", 5),
            ("lemon_juice", 5), ("salt", 2)], 207, [("1 plate", 150)], ["bhel", "jhalmuri"]),
    recipe("pani-puri", "Pani puri",
           [("sooji", 30), ("oil", 8), ("potato_boiled", 40), ("chana_cooked", 20),
            ("water", 150), ("tamarind", 10), ("sugar", 5), ("salt", 2)], 257,
           [("1 plate (6 puri, with pani)", 257)], ["golgappa", "puchka", "gol gappe"]),
    recipe("sabudana-khichdi", "Sabudana khichdi",
           [("sabudana", 150), ("water", 90), ("potato_boiled", 100), ("peanuts", 40),
            ("ghee", 20), ("sugar", 3), ("salt", 4)], 390, [KATORI], ["sago khichdi"]),
    recipe("dahi-vada", "Dahi vada",
           [("urad_raw", 100), ("water", 60), ("oil", 25), ("curd", 300), ("sugar", 10),
            ("salt", 4)], 480, [("1 plate (2 vadas)", 150)], ["dahi bhalla", "thayir vadai"]),
    recipe("kachori", "Kachori",
           [("maida", 150), ("oil", 70), ("water", 60), ("moong_raw", 50), ("salt", 4)],
           290, [("1 kachori", 50)], ["khasta kachori", "moong dal kachori"],
           note="deep-fried; 30 g oil in the dough and ~40 g taken up in frying"),
    recipe("paneer-pakora", "Paneer pakora",
           [("paneer", 200), ("besan", 80), ("water", 80), ("oil", 40), ("salt", 4)], 360,
           [("1 piece", 25)], ["paneer pakoda"]),
    recipe("sev", "Sev / bhujia",
           [("besan", 100), ("water", 50), ("oil", 45), ("salt", 2)], 150,
           [TBSP, ("1 small bowl", 30)], ["bhujia", "namkeen", "aloo bhujia"],
           note="deep-fried besan; commercial namkeen varies"),

    # ------------------------------------------------------------------ sweets
    recipe("gulab-jamun", "Gulab jamun",
           [("milk_powder", 100), ("maida", 25), ("ghee", 15), ("milk", 40), ("oil", 20),
            ("sugar", 100), ("water", 70)], 350, [("1 piece", 40)], ["gulab jamoon"],
           note="milk-powder dough, fried and soaked; syrup taken up estimated"),
    recipe("jalebi", "Jalebi",
           [("maida", 100), ("curd", 20), ("water", 110), ("oil", 40), ("sugar", 100)], 280,
           [("1 piece", 25)], ["jilebi"], note="oil and syrup taken up estimated"),
    recipe("rasgulla", "Rasgulla",
           [("paneer", 150), ("sugar", 110), ("water", 170)], 440, [("1 piece", 50)],
           ["rosogolla", "rasagola"],
           note="whole-milk chhena valued as fresh cheese; syrup taken up estimated"),
    recipe("rasmalai", "Rasmalai",
           [("paneer", 150), ("milk", 500), ("sugar", 70)], 520, [("1 piece with milk", 80)],
           ["ras malai"], note="milk reduced to about 60%; chhena valued as fresh cheese"),
    recipe("kheer", "Kheer (rice)",
           [("milk", 1000), ("rice_raw", 50), ("sugar", 80), ("almonds", 15)], 650,
           [KATORI], ["rice kheer", "payasam", "chawal ki kheer"]),
    recipe("semiya-payasam", "Semiya payasam",
           [("vermicelli", 50), ("milk", 750), ("sugar", 70), ("ghee", 10), ("cashew", 10)],
           700, [KATORI], ["vermicelli kheer", "seviyan"]),
    recipe("gajar-halwa", "Gajar halwa",
           [("carrot", 500), ("milk", 500), ("sugar", 100), ("ghee", 40), ("cashew", 15)],
           550, [KATORI_CURD], ["gajar ka halwa", "carrot halwa"]),
    recipe("suji-halwa", "Suji halwa",
           [("sooji", 100), ("ghee", 60), ("sugar", 100), ("water", 300), ("cashew", 10)],
           450, [KATORI_CURD], ["sheera", "rava kesari", "sooji halwa"]),
    recipe("kaju-katli", "Kaju katli",
           [("cashew", 200), ("sugar", 120), ("ghee", 5), ("water", 60)], 320,
           [("1 piece", 15)], ["kaju barfi", "kaju katri"]),
    recipe("kulfi", "Kulfi",
           [("milk", 1000), ("sugar", 80), ("almonds", 15)], 490, [("1 kulfi", 70)],
           note="milk reduced to about 40%"),
    recipe("mishti-doi", "Mishti doi",
           [("milk", 600), ("curd", 50), ("jaggery", 60)], 520, [("1 cup", 100)],
           ["sweet curd", "mishti dahi"]),

    # ------------------------------------------------------------------ drinks
    recipe("chai-no-sugar", "Chai without sugar",
           [("tea", 100), ("milk", 100)], 180, [CUP_CHAI], ["unsweetened chai", "tea no sugar"]),
    recipe("filter-coffee", "Filter coffee",
           [("coffee", 60), ("milk", 120), ("sugar", 8)], 180, [CUP_CHAI],
           ["south indian coffee", "kaapi", "coffee with milk"]),
    recipe("sweet-lassi", "Sweet lassi",
           [("curd", 200), ("milk", 50), ("sugar", 25), ("water", 25)], 300, [GLASS],
           ["lassi", "meethi lassi"]),
    recipe("salted-lassi", "Salted lassi",
           [("curd", 200), ("water", 100), ("salt", 2)], 302, [GLASS], ["namkeen lassi"]),
    recipe("chaas", "Chaas (spiced buttermilk)",
           [("curd", 100), ("water", 200), ("salt", 2), ("coriander", 2)], 304, [GLASS],
           ["chaas", "mattha", "majjige", "moru", "indian buttermilk"]),
    recipe("mango-lassi", "Mango lassi",
           [("curd", 150), ("mango", 100), ("milk", 50), ("sugar", 15)], 315, [GLASS]),
    recipe("nimbu-pani", "Nimbu pani",
           [("lemon_juice", 30), ("sugar", 20), ("water", 250), ("salt", 1)], 301, [GLASS],
           ["nimbu paani", "shikanji", "lemonade"]),
    recipe("badam-milk", "Badam milk",
           [("milk", 200), ("almonds", 15), ("sugar", 12)], 227, [GLASS], ["badam doodh"]),

    # ---------------------------------------------------------- accompaniments
    recipe("raita", "Cucumber raita",
           [("curd", 200), ("cucumber", 80), ("salt", 2)], 282, [KATORI_CURD],
           ["raita", "kheera raita"]),
    recipe("coconut-chutney", "Coconut chutney",
           [("coconut", 100), ("chana_cooked", 15), ("green_chilli", 5), ("water", 60),
            ("oil", 5), ("salt", 2)], 187, [TBSP, ("1 small bowl", 50)], ["nariyal chutney"]),
    recipe("green-chutney", "Green chutney (mint-coriander)",
           [("coriander", 60), ("mint", 30), ("green_chilli", 10), ("lemon_juice", 15),
            ("water", 20), ("salt", 2)], 137, [TBSP], ["hari chutney", "pudina chutney"]),
    recipe("mango-pickle", "Mango pickle",
           [("mango", 500), ("mustard_oil", 150), ("salt", 60)], 700, [TSP, TBSP],
           ["aam ka achar", "achar", "pickle"],
           note="green mango valued as ripe mango; oil-heavy North Indian style"),
)
